### ISSUE TITLE
Deploy 9c-main-v2

### ISSUE THREAD

**Issue by area363** [planetarium/9c-infra#117]

**Comment by area363** [comment]
- [ ] 1. Deploy 9c-main-v2
- [ ] 2. Sync 9c-main-v2 nodes with 9c-main
- [ ] 3. Import 9c-main secrets to 9c-main-v2
- [ ] 4. Import 9c-onboarding cluster services to 9c-main-v2
- [ ] 5. Migrate Route53 and Cloudflare routing to 9c-main-v2 (RPC, miner, seed, full-state, dp, etc)
- [ ] 6. Check for other services that directly use ELB addresses and change these to new addresses (e.g. onboarding-portal).

**Comment by Atralupus** [comment]
+ fluent bit config migration

**Comment by area363** [comment]
<List of Mainnet Services to Migrate>
1. Miner (miner-2, 3)
2. RPC (remote-headless-1 ~ 5)
3. Full-State
4. DP
5. Explorer
6. Seed
7. Snapshot

**Comment by area363** [comment]
The original 9c-main cluster is not completely turned off but we've officially began using 9c-main-v2 cluster so I'm closing this issue.
