### ISSUE TITLE
DataProvider from internal-v2 doesn't insert data to its DB

### ISSUE THREAD

**Issue by sky1045** [planetarium/9c-infra#88]
SSIA

**Comment by area363** [comment]
Did you include `NC_Render=true` to the environment variable?

**Comment by sky1045** [comment]
oh, let me try that. it seems that only `data-provider-db` sets it true and it inserts data alone, i didn't recognize that

**Comment by sky1045** [comment]
thanks, i checked it inserts data as i set `NC_Render=true`. closing

**Comment by area363** [comment]
Thanks for checking. You won't have include`NC_Render=true`  from the next release 😅
